pragma Singleton

import Quickshell
import QtQuick

Singleton {
    id: root
    readonly property color bg: "#3a3a3a"
    readonly property color fg: "#eeeeec"
    readonly property color text: "#ffffff"
    readonly property color base: "#2d2d2d"
    readonly property color caret: "#f7f7f7"
    readonly property color selectedBg: "#15539e"
    readonly property color selectedFg: "#ffffff"
    readonly property color selectedBorder: "#0f3b71"
    readonly property color border: "#212121"
    readonly property color borderAlt: "#0c0c0c"
    readonly property color borderEdge: "#eeeeecf7"
    readonly property color headerBar: "#323232"
    readonly property color menu: "#2F2F2F"
    readonly property color popover: "#3a3a3a"
    readonly property color popoverHover: "#474747"
    readonly property color scrollbarBg: "#313131"
    readonly property color scrollbarSlider: "#A4A4A3"
    readonly property color scrollbarSliderHover: "#C9C9C7"
    readonly property color scrollbarSliderActive: "#1B6ACA"
    readonly property color warning: "#f57900"
    readonly property color error: "#cc0000"
    readonly property color success: "#26ab62"
    readonly property color destructive: "#b2161d"
    readonly property color dropTarget: "#4e9a06"
    readonly property color link: "#3584e4"
    readonly property color linkVisited: "#1b6bcb"
    readonly property color darkFill: "#282828"
    readonly property color osdBg: "#252525"
    readonly property color osdFg: "#eeeeec"
    readonly property color osdText: "#ffffff"
    readonly property color osdBorder: "#000000B3"
    readonly property color sidebar: "#323232"
    readonly property color hover: "#eeeeec0d"
    readonly property color tooltipBorder: "#ffffff1a"
    readonly property color shadow: "#0000001a"
    readonly property color disabledFg: "#949491"
    readonly property color disabledBg: "#313131"
    readonly property color disabledBorder: "#1c1c1c"
    readonly property color backdropBg: "#363636"
    readonly property color backdropFg: "#929291"
    readonly property color backdropText: "#d6d6d4"
    readonly property color backdropBorder: "#212121"
    readonly property color accent: "#15539e"
    readonly property color accentBorder: "#0b2c54"
    readonly property color checkRadioBg: "#1f6bc0"
    readonly property color checkRadioFg: "#ffffff"
    readonly property color checkRadioBorder: "#061d38"
}
